version: '3.8'

services:
  nominatim-importer:
    image: mediagis/nominatim:5.0
    container_name: nominatim-importer
    expose:
      - "5432"
    env_file: "importer/vars.env"
    volumes:
      - ./nominatim-data:/var/lib/postgresql/16/main
      - ./importer/maps/:/data/:ro
    networks:
      - mapops

  photon-importer:
    image: local/pothon
    build:
      context: ./importer/
      args:
        PHOTON_VERSION: 0.6.2
    command: "import"
    container_name: photon-importer
    env_file: "importer/vars.env"
    depends_on:
      - nominatim-importer
    volumes:
      - ./photon-data:/photon
    networks:
      - mapops

networks:
  mapops:
    attachable: true
    name: mapops
